apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-backend
# specification
spec:
  # 副本数量
  replicas: 3
  selector:
    matchLabels:
      app: webook-backend
  # template 描述的是你的 POD 是什么样的
  template:
    metadata:
      labels:
        app: webook-backend
    # POD 的具体信息
    spec:
      containers:
        - name: webook-backend
          image: shgqmrf/webook:v0.0.1 
          ports:
            - containerPort: 8001